build-system: Autotools rebuild from 0.6.5-66-gda484d0
Based-on: da484d02b3a1f83a948ed12e8ff8ddc33e818ac5

diff --git a/src/missing/strlcat/Makefile.in b/src/missing/strlcat/Makefile.in
--- a/src/missing/strlcat/Makefile.in
+++ b/src/missing/strlcat/Makefile.in
@@ -15,6 +15,34 @@
 
 @SET_MAKE@
 
+#
+#  Copyright (c) 2016, The OpenThread Authors.
+#  All rights reserved.
+#
+#  Redistribution and use in source and binary forms, with or without
+#  modification, are permitted provided that the following conditions are met:
+#  1. Redistributions of source code must retain the above copyright
+#     notice, this list of conditions and the following disclaimer.
+#  2. Redistributions in binary form must reproduce the above copyright
+#     notice, this list of conditions and the following disclaimer in the
+#     documentation and/or other materials provided with the distribution.
+#  3. Neither the name of the copyright holder nor the
+#     names of its contributors may be used to endorse or promote products
+#     derived from this software without specific prior written permission.
+#
+#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
+#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
+#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
+#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
+#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
+#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
+#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
+#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
+#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
+#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+#  POSSIBILITY OF SUCH DAMAGE.
+#
+
 VPATH = @srcdir@
 pkgdatadir = $(datadir)/@PACKAGE@
 pkgincludedir = $(includedir)/@PACKAGE@
@@ -34,9 +62,11 @@ PRE_UNINSTALL = :
 POST_UNINSTALL = :
 build_triplet = @build@
 host_triplet = @host@
-@BUILD_PLUGTEST_TRUE@bin_PROGRAMS = smcp-plugtest-server$(EXEEXT) \
-@BUILD_PLUGTEST_TRUE@	smcp-plugtest-client$(EXEEXT)
-subdir = src/plugtest
+check_PROGRAMS = strlcat_test$(EXEEXT)
+TESTS = strlcat_test$(EXEEXT)
+@MISSING_STRLCAT_TRUE@am__append_1 = libstrlcat.la \
+@MISSING_STRLCAT_TRUE@	../strlcpy/libstrlcpy.la
+subdir = src/missing/strlcat
 DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
@@ -50,18 +80,19 @@ CONFIG_HEADER = $(top_builddir)/src/config.h \
 	$(top_builddir)/src/smcp/smcp-config.h
 CONFIG_CLEAN_FILES =
 CONFIG_CLEAN_VPATH_FILES =
-am__installdirs = "$(DESTDIR)$(bindir)"
-PROGRAMS = $(bin_PROGRAMS)
-am_smcp_plugtest_client_OBJECTS = main-client.$(OBJEXT)
-smcp_plugtest_client_OBJECTS = $(am_smcp_plugtest_client_OBJECTS)
-smcp_plugtest_client_DEPENDENCIES = ../smcp/libsmcp.la
+LTLIBRARIES = $(noinst_LTLIBRARIES)
+libstrlcat_la_LIBADD =
+am__libstrlcat_la_SOURCES_DIST = strlcat.c strlcat.h
+@MISSING_STRLCAT_TRUE@am_libstrlcat_la_OBJECTS =  \
+@MISSING_STRLCAT_TRUE@	libstrlcat_la-strlcat.lo
+libstrlcat_la_OBJECTS = $(am_libstrlcat_la_OBJECTS)
 AM_V_lt = $(am__v_lt_@AM_V@)
 am__v_lt_ = $(am__v_lt_@AM_DEFAULT_V@)
 am__v_lt_0 = --silent
-am_smcp_plugtest_server_OBJECTS = main-server.$(OBJEXT) \
-	plugtest-server.$(OBJEXT)
-smcp_plugtest_server_OBJECTS = $(am_smcp_plugtest_server_OBJECTS)
-smcp_plugtest_server_DEPENDENCIES = ../smcp/libsmcp.la
+@MISSING_STRLCAT_TRUE@am_libstrlcat_la_rpath =
+am_strlcat_test_OBJECTS = strlcat_test-strlcat_test.$(OBJEXT)
+strlcat_test_OBJECTS = $(am_strlcat_test_OBJECTS)
+strlcat_test_DEPENDENCIES = $(am__append_1)
 DEFAULT_INCLUDES = -I.@am__isrc@ -I$(top_builddir)/src -I$(top_builddir)/src/smcp
 depcomp = $(SHELL) $(top_srcdir)/m4/depcomp
 am__depfiles_maybe = depfiles
@@ -88,10 +119,9 @@ am__v_CCLD_0 = @echo "  CCLD  " $@;
 AM_V_GEN = $(am__v_GEN_@AM_V@)
 am__v_GEN_ = $(am__v_GEN_@AM_DEFAULT_V@)
 am__v_GEN_0 = @echo "  GEN   " $@;
-SOURCES = $(smcp_plugtest_client_SOURCES) \
-	$(smcp_plugtest_server_SOURCES)
-DIST_SOURCES = $(smcp_plugtest_client_SOURCES) \
-	$(smcp_plugtest_server_SOURCES)
+SOURCES = $(libstrlcat_la_SOURCES) $(strlcat_test_SOURCES)
+DIST_SOURCES = $(am__libstrlcat_la_SOURCES_DIST) \
+	$(strlcat_test_SOURCES)
 ETAGS = etags
 CTAGS = ctags
 am__tty_colors = \
@@ -131,6 +161,8 @@ INSTALL_SCRIPT = @INSTALL_SCRIPT@
 INSTALL_STRIP_PROGRAM = @INSTALL_STRIP_PROGRAM@
 LD = @LD@
 LDFLAGS = @LDFLAGS@
+LIBNYOCI_CFLAGS = @LIBNYOCI_CFLAGS@
+LIBNYOCI_LIBS = @LIBNYOCI_LIBS@
 LIBOBJS = @LIBOBJS@
 LIBS = @LIBS@
 LIBTOOL = @LIBTOOL@
@@ -140,14 +172,13 @@ LOAD_ALL_SYMBOLS_FLAG = @LOAD_ALL_SYMBOLS_FLAG@
 LTLIBOBJS = @LTLIBOBJS@
 MAKEINFO = @MAKEINFO@
 MANIFEST_TOOL = @MANIFEST_TOOL@
+MISSING_CPPFLAGS = @MISSING_CPPFLAGS@
+MISSING_LIBADD = @MISSING_LIBADD@
 MKDIR_P = @MKDIR_P@
 NM = @NM@
 NMEDIT = @NMEDIT@
 OBJDUMP = @OBJDUMP@
 OBJEXT = @OBJEXT@
-OPENSSL_INCLUDES = @OPENSSL_INCLUDES@
-OPENSSL_LDFLAGS = @OPENSSL_LDFLAGS@
-OPENSSL_LIBS = @OPENSSL_LIBS@
 OTOOL = @OTOOL@
 OTOOL64 = @OTOOL64@
 PACKAGE = @PACKAGE@
@@ -159,9 +190,8 @@ PACKAGE_URL = @PACKAGE_URL@
 PACKAGE_VERSION = @PACKAGE_VERSION@
 PATH_SEPARATOR = @PATH_SEPARATOR@
 PKG_CONFIG = @PKG_CONFIG@
-PTHREAD_CC = @PTHREAD_CC@
-PTHREAD_CFLAGS = @PTHREAD_CFLAGS@
-PTHREAD_LIBS = @PTHREAD_LIBS@
+PKG_CONFIG_LIBDIR = @PKG_CONFIG_LIBDIR@
+PKG_CONFIG_PATH = @PKG_CONFIG_PATH@
 RANLIB = @RANLIB@
 SED = @SED@
 SET_MAKE = @SET_MAKE@
@@ -180,7 +210,6 @@ am__leading_dot = @am__leading_dot@
 am__quote = @am__quote@
 am__tar = @am__tar@
 am__untar = @am__untar@
-ax_pthread_config = @ax_pthread_config@
 bindir = @bindir@
 build = @build@
 build_alias = @build_alias@
@@ -221,17 +250,24 @@ target_alias = @target_alias@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-AM_CPPFLAGS = -I.. -I$(top_srcdir)/src
-AM_LIBS = $(CODE_COVERAGE_LDFLAGS)
-AM_CFLAGS = $(CFLAGS) $(CODE_COVERAGE_CFLAGS)
-@BUILD_PLUGTEST_TRUE@TESTS = selftest.sh
-smcp_plugtest_server_SOURCES = main-server.c plugtest-server.c plugtest-server.h
-smcp_plugtest_server_LDADD = ../smcp/libsmcp.la
-smcp_plugtest_client_SOURCES = main-client.c
-smcp_plugtest_client_LDADD = ../smcp/libsmcp.la
-TESTS_ENVIRONMENT = builddir='$(builddir)'
-EXTRA_DIST = selftest.sh README.md
-DISTCLEANFILES = .deps Makefile
+strlcat_test_SOURCES = strlcat_test.c
+strlcat_test_CPPFLAGS = \
+	$(AM_CPPFLAGS)                    \
+	$(MISSING_CPPFLAGS)               \
+	$(NULL)
+
+strlcat_test_LDADD = $(NULL) $(am__append_1)
+@MISSING_STRLCAT_TRUE@noinst_LTLIBRARIES = libstrlcat.la
+@MISSING_STRLCAT_TRUE@libstrlcat_la_SOURCES = \
+@MISSING_STRLCAT_TRUE@	strlcat.c                         \
+@MISSING_STRLCAT_TRUE@	strlcat.h                         \
+@MISSING_STRLCAT_TRUE@	$(NULL)
+
+@MISSING_STRLCAT_TRUE@libstrlcat_la_CPPFLAGS = \
+@MISSING_STRLCAT_TRUE@	$(AM_CPPFLAGS)                    \
+@MISSING_STRLCAT_TRUE@	$(MISSING_CPPFLAGS)               \
+@MISSING_STRLCAT_TRUE@	$(NULL)
+
 all: all-am
 
 .SUFFIXES:
@@ -245,9 +281,9 @@ $(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
 	      exit 1;; \
 	  esac; \
 	done; \
-	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign src/plugtest/Makefile'; \
+	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign src/missing/strlcat/Makefile'; \
 	$(am__cd) $(top_srcdir) && \
-	  $(AUTOMAKE) --foreign src/plugtest/Makefile
+	  $(AUTOMAKE) --foreign src/missing/strlcat/Makefile
 .PRECIOUS: Makefile
 Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
 	@case '$?' in \
@@ -266,55 +302,29 @@ $(top_srcdir)/configure:  $(am__configure_deps)
 $(ACLOCAL_M4):  $(am__aclocal_m4_deps)
 	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
 $(am__aclocal_m4_deps):
-install-binPROGRAMS: $(bin_PROGRAMS)
-	@$(NORMAL_INSTALL)
-	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
-	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
-	for p in $$list; do echo "$$p $$p"; done | \
-	sed 's/$(EXEEXT)$$//' | \
-	while read p p1; do if test -f $$p || test -f $$p1; \
-	  then echo "$$p"; echo "$$p"; else :; fi; \
-	done | \
-	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
-	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
-	sed 'N;N;N;s,\n, ,g' | \
-	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
-	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
-	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
-	    else { print "f", $$3 "/" $$4, $$1; } } \
-	  END { for (d in files) print "f", d, files[d] }' | \
-	while read type dir files; do \
-	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
-	    test -z "$$files" || { \
-	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
-	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
-	    } \
-	; done
 
-uninstall-binPROGRAMS:
-	@$(NORMAL_UNINSTALL)
-	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
-	files=`for p in $$list; do echo "$$p"; done | \
-	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
-	      -e 's/$$/$(EXEEXT)/' `; \
-	test -n "$$list" || exit 0; \
-	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
-	cd "$(DESTDIR)$(bindir)" && rm -f $$files
+clean-noinstLTLIBRARIES:
+	-test -z "$(noinst_LTLIBRARIES)" || rm -f $(noinst_LTLIBRARIES)
+	@list='$(noinst_LTLIBRARIES)'; for p in $$list; do \
+	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
+	  test "$$dir" != "$$p" || dir=.; \
+	  echo "rm -f \"$${dir}/so_locations\""; \
+	  rm -f "$${dir}/so_locations"; \
+	done
+libstrlcat.la: $(libstrlcat_la_OBJECTS) $(libstrlcat_la_DEPENDENCIES) $(EXTRA_libstrlcat_la_DEPENDENCIES) 
+	$(AM_V_CCLD)$(LINK) $(am_libstrlcat_la_rpath) $(libstrlcat_la_OBJECTS) $(libstrlcat_la_LIBADD) $(LIBS)
 
-clean-binPROGRAMS:
-	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
+clean-checkPROGRAMS:
+	@list='$(check_PROGRAMS)'; test -n "$$list" || exit 0; \
 	echo " rm -f" $$list; \
 	rm -f $$list || exit $$?; \
 	test -n "$(EXEEXT)" || exit 0; \
 	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
 	echo " rm -f" $$list; \
 	rm -f $$list
-smcp-plugtest-client$(EXEEXT): $(smcp_plugtest_client_OBJECTS) $(smcp_plugtest_client_DEPENDENCIES) $(EXTRA_smcp_plugtest_client_DEPENDENCIES) 
-	@rm -f smcp-plugtest-client$(EXEEXT)
-	$(AM_V_CCLD)$(LINK) $(smcp_plugtest_client_OBJECTS) $(smcp_plugtest_client_LDADD) $(LIBS)
-smcp-plugtest-server$(EXEEXT): $(smcp_plugtest_server_OBJECTS) $(smcp_plugtest_server_DEPENDENCIES) $(EXTRA_smcp_plugtest_server_DEPENDENCIES) 
-	@rm -f smcp-plugtest-server$(EXEEXT)
-	$(AM_V_CCLD)$(LINK) $(smcp_plugtest_server_OBJECTS) $(smcp_plugtest_server_LDADD) $(LIBS)
+strlcat_test$(EXEEXT): $(strlcat_test_OBJECTS) $(strlcat_test_DEPENDENCIES) $(EXTRA_strlcat_test_DEPENDENCIES) 
+	@rm -f strlcat_test$(EXEEXT)
+	$(AM_V_CCLD)$(LINK) $(strlcat_test_OBJECTS) $(strlcat_test_LDADD) $(LIBS)
 
 mostlyclean-compile:
 	-rm -f *.$(OBJEXT)
@@ -322,9 +332,8 @@ mostlyclean-compile:
 distclean-compile:
 	-rm -f *.tab.c
 
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/main-client.Po@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/main-server.Po@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/plugtest-server.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libstrlcat_la-strlcat.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/strlcat_test-strlcat_test.Po@am__quote@
 
 .c.o:
 @am__fastdepCC_TRUE@	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
@@ -346,6 +355,27 @@ distclean-compile:
 @AMDEP_TRUE@@am__fastdepCC_FALSE@	$(AM_V_CC)source='$<' object='$@' libtool=yes @AMDEPBACKSLASH@
 @AMDEP_TRUE@@am__fastdepCC_FALSE@	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) @AMDEPBACKSLASH@
 @am__fastdepCC_FALSE@	$(AM_V_CC@am__nodep@)$(LTCOMPILE) -c -o $@ $<
+
+libstrlcat_la-strlcat.lo: strlcat.c
+@am__fastdepCC_TRUE@	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libstrlcat_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT libstrlcat_la-strlcat.lo -MD -MP -MF $(DEPDIR)/libstrlcat_la-strlcat.Tpo -c -o libstrlcat_la-strlcat.lo `test -f 'strlcat.c' || echo '$(srcdir)/'`strlcat.c
+@am__fastdepCC_TRUE@	$(AM_V_at)$(am__mv) $(DEPDIR)/libstrlcat_la-strlcat.Tpo $(DEPDIR)/libstrlcat_la-strlcat.Plo
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	$(AM_V_CC)source='strlcat.c' object='libstrlcat_la-strlcat.lo' libtool=yes @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCC_FALSE@	$(AM_V_CC@am__nodep@)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libstrlcat_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o libstrlcat_la-strlcat.lo `test -f 'strlcat.c' || echo '$(srcdir)/'`strlcat.c
+
+strlcat_test-strlcat_test.o: strlcat_test.c
+@am__fastdepCC_TRUE@	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(strlcat_test_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT strlcat_test-strlcat_test.o -MD -MP -MF $(DEPDIR)/strlcat_test-strlcat_test.Tpo -c -o strlcat_test-strlcat_test.o `test -f 'strlcat_test.c' || echo '$(srcdir)/'`strlcat_test.c
+@am__fastdepCC_TRUE@	$(AM_V_at)$(am__mv) $(DEPDIR)/strlcat_test-strlcat_test.Tpo $(DEPDIR)/strlcat_test-strlcat_test.Po
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	$(AM_V_CC)source='strlcat_test.c' object='strlcat_test-strlcat_test.o' libtool=no @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCC_FALSE@	$(AM_V_CC@am__nodep@)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(strlcat_test_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o strlcat_test-strlcat_test.o `test -f 'strlcat_test.c' || echo '$(srcdir)/'`strlcat_test.c
+
+strlcat_test-strlcat_test.obj: strlcat_test.c
+@am__fastdepCC_TRUE@	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(strlcat_test_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT strlcat_test-strlcat_test.obj -MD -MP -MF $(DEPDIR)/strlcat_test-strlcat_test.Tpo -c -o strlcat_test-strlcat_test.obj `if test -f 'strlcat_test.c'; then $(CYGPATH_W) 'strlcat_test.c'; else $(CYGPATH_W) '$(srcdir)/strlcat_test.c'; fi`
+@am__fastdepCC_TRUE@	$(AM_V_at)$(am__mv) $(DEPDIR)/strlcat_test-strlcat_test.Tpo $(DEPDIR)/strlcat_test-strlcat_test.Po
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	$(AM_V_CC)source='strlcat_test.c' object='strlcat_test-strlcat_test.obj' libtool=no @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCC_FALSE@	$(AM_V_CC@am__nodep@)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(strlcat_test_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o strlcat_test-strlcat_test.obj `if test -f 'strlcat_test.c'; then $(CYGPATH_W) 'strlcat_test.c'; else $(CYGPATH_W) '$(srcdir)/strlcat_test.c'; fi`
 
 mostlyclean-libtool:
 	-rm -f *.lo
@@ -529,13 +559,11 @@ distdir: $(DISTFILES)
 	  fi; \
 	done
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
 	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
-all-am: Makefile $(PROGRAMS)
+all-am: Makefile $(LTLIBRARIES)
 installdirs:
-	for dir in "$(DESTDIR)$(bindir)"; do \
-	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
-	done
 install: install-am
 install-exec: install-exec-am
 install-data: install-data-am
@@ -562,14 +590,14 @@ clean-generic:
 distclean-generic:
 	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
 	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
-	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)
 
 maintainer-clean-generic:
 	@echo "This command is intended for maintainers to use"
 	@echo "it deletes files that may require special tools to rebuild."
 clean: clean-am
 
-clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am
+clean-am: clean-checkPROGRAMS clean-generic clean-libtool \
+	clean-noinstLTLIBRARIES mostlyclean-am
 
 distclean: distclean-am
 	-rm -rf ./$(DEPDIR)
@@ -595,7 +623,7 @@ install-dvi: install-dvi-am
 
 install-dvi-am:
 
-install-exec-am: install-binPROGRAMS
+install-exec-am:
 
 install-html: install-html-am
 
@@ -635,26 +663,24 @@ ps: ps-am
 
 ps-am:
 
-uninstall-am: uninstall-binPROGRAMS
+uninstall-am:
 
 .MAKE: check-am install-am install-strip
 
 .PHONY: CTAGS GTAGS all all-am check check-TESTS check-am clean \
-	clean-binPROGRAMS clean-generic clean-libtool ctags distclean \
-	distclean-compile distclean-generic distclean-libtool \
-	distclean-tags distdir dvi dvi-am html html-am info info-am \
-	install install-am install-binPROGRAMS install-data \
-	install-data-am install-dvi install-dvi-am install-exec \
-	install-exec-am install-html install-html-am install-info \
-	install-info-am install-man install-pdf install-pdf-am \
-	install-ps install-ps-am install-strip installcheck \
-	installcheck-am installdirs maintainer-clean \
+	clean-checkPROGRAMS clean-generic clean-libtool \
+	clean-noinstLTLIBRARIES ctags distclean distclean-compile \
+	distclean-generic distclean-libtool distclean-tags distdir dvi \
+	dvi-am html html-am info info-am install install-am \
+	install-data install-data-am install-dvi install-dvi-am \
+	install-exec install-exec-am install-html install-html-am \
+	install-info install-info-am install-man install-pdf \
+	install-pdf-am install-ps install-ps-am install-strip \
+	installcheck installcheck-am installdirs maintainer-clean \
 	maintainer-clean-generic mostlyclean mostlyclean-compile \
 	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
-	tags uninstall uninstall-am uninstall-binPROGRAMS
+	tags uninstall uninstall-am
 
-
-@CODE_COVERAGE_RULES@
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
